### PR TITLE
[Dutch] Update language.php and global.po

### PR DESCRIPTION
**Pull request by BlackTiger63**
Minor changes on the bottom of the language.php. Things where missing, and not or wrongly translated.
Loads of additions to global.po and a lot of changes to wrongly translated existing translations and grammatical errors.

### CODE REVIEW

**Comment by pH-7** [comment]
That's brilliant @BlackTiger63! 

Just notice a little thing. Both files are in the root directory.
However, `language.php` file should be in `_protected/app/langs/nl_NL/` directory 
and ` global.po` file should be in `_protected/app/langs/nl_NL/LC_MESSAGES/` directory.

Surely, once merged, I will update the config.ini file mentioning your name too.

**Comment by BlackTiger63** [comment]
Thank you very much.
Sorry they are in the wrong directory, I thought it would be automatically placed in the correct folder. I'll keep that in mind for next time.
Thank you!

**Comment by BlackTiger63** [comment]
Deleted the old files and put the new files on the correct location now. :)

**Comment by pH-7** [comment]
Awesome @BlackTiger63 You succeed it! As you can see at https://github.com/pH7Software/pH7-Internationalization/pull/10/files, it is now also easier to see the diffs with your changes :)

**Comment by BlackTiger63** [comment]
Great!

**Pull request merged**
