### PR TITLE
German Language

### PR DESCRIPTION
**Pull request by Nitroziklop**
Hello, when does the German come with pH7CMS Social Network? Or how can I translate the language from English in German?

### CODE REVIEW

**Comment by Nitroziklop** [comment]
Sorry i need German not France! What is it ?

**Comment by pH-7** [comment]
Hi @Nitroziklop 
German isn't currently available, but you CAN translate it "easily" with Gettext. 
More details: https://ph7cms.com/doc/en/how-to-translate-to-another-language

P.S. Next time, please create an issue (https://github.com/pH7Software/pH7-Internationalization/issues), but not a Pull Request for **questions** 😄 

I'm closing this by now.

**Comment by Nitroziklop** [comment]
Thx for Help !!! :)

**Comment by Nitroziklop** [comment]
I have try to change global.po on in German, however, after change nothing has happened, has remained in spite of demm English! I do not know which file I should exactly work on?

**Pull request closed without merging**
